apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discourse-stack-deployment
  namespace: {{ namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: discourse-stack
        environment: {{ environment }}
    spec:
      containers:
        - name: discourse
          image: {{ &discourseStack.discourseImageName }}:{{ &discourseStack.discourseImageVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: DISCOURSE_HOSTNAME
              value: testlab-discourse.test-datalabs.nerc.ac.uk
            - name: DISCOURSE_PASSWORD
              value: bitnami1
            - name: DISCOURSE_POSTGRESQL_NAME
              value: bitnami_application
            - name: DISCOURSE_POSTGRESQL_PASSWORD
              value: bitnami1
            - name: DISCOURSE_POSTGRESQL_USERNAME
              value: bn_discourse
            - name: DISCOURSE_SITE_NAME
              value: {{ discourseStack.discourseSiteName }}
            - name: POSTGRESQL_CLIENT_CREATE_DATABASE_NAME
              value: bitnami_application
            - name: POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD
              value: bitnami1
            - name: POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
              value: bn_discourse
            - name: POSTGRESQL_HOST
              value: localhost
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_ROOT_PASSWORD
              value: bitnami1
            - name: POSTGRESQL_ROOT_USER
              value: postgres
            - name: REDIS_HOST
              value: localhost
            - name: REDIS_PASSWORD
              value: bitnami1
            - name: REDIS_PORT_NUMBER
              value: "6379"
          ports:
            - containerPort: 3000
        - name: sidekiq
          image: {{ &discourseStack.sidekiqImageName }}:{{ &discourseStack.sidekiqImageVersion }}
          imagePullPolicy: IfNotPresent
          command: ["./app-entrypoint.sh", "nami", "start", "--foreground", "discourse-sidekiq"]
          env:
            - name: DISCOURSE_PASSWORD
              value: bitnami1
            - name: DISCOURSE_POSTGRESQL_NAME
              value: bitnami_application
            - name: DISCOURSE_POSTGRESQL_PASSWORD
              value: bitnami1
            - name: DISCOURSE_POSTGRESQL_USERNAME
              value: bn_discourse
            - name: DISCOURSE_SITE_NAME
              value: {{ discourseStack.discourseSiteName }}
            - name: POSTGRESQL_CLIENT_CREATE_DATABASE_NAME
              value: bitnami_application
            - name: POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD
              value: bitnami1
            - name: POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
              value: bn_discourse
            - name: POSTGRESQL_HOST
              value: localhost
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_ROOT_PASSWORD
              value: bitnami1
            - name: POSTGRESQL_ROOT_USER
              value: postgres
            - name: REDIS_HOST
              value: localhost
            - name: REDIS_PASSWORD
              value: bitnami1
            - name: REDIS_PORT_NUMBER
              value: "6379"
        - name: postgresql
          image: {{ &discourseStack.postgresqlImageName }}:{{ &discourseStack.postgresqlImageVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRESQL_PASSWORD
              value: bitnami1
        - name: redis
          image: {{ &discourseStack.redisImageName }}:{{ &discourseStack.redisImageVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_PASSWORD
              value: bitnami1
---
apiVersion: v1
kind: Service
metadata:
  name: discourse-stack-service
  namespace: {{ namespace }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: discourse-stack
  type: NodePort
