apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discourse-stack-deployment
  namespace: {{ namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: discourse-stack
        environment: {{ environment }}
    spec:
      containers:
        - name: discourse
          image: {{ &discourseStack.discourseImageName }}:{{ &discourseStack.discourseImageVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRESQL_HOST
              value: localhost
            - name: POSTGRESQL_ROOT_USER
              value: postgres
            - name: POSTGRESQL_CLIENT_CREATE_DATABASE_NAME
              value: bitnami_application
            - name: POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
              value: bn_discourse
            - name: POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD
              value: bitnami1
            - name: DISCOURSE_POSTGRESQL_NAME
              value: bitnami_application
            - name: DISCOURSE_POSTGRESQL_USERNAME
              value: bn_discourse
            - name: DISCOURSE_POSTGRESQL_PASSWORD
              value: bitnami1
            - name: POSTGRESQL_HOST
              value: localhost
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: REDIS_HOST
              value: localhost
            - name: REDIS_PORT_NUMBER
              value: "6379"
            - name: DISCOURSE_SITE_NAME
              value: {{ discourseStack.discourseSiteName }}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: discourse-data
              mountPath: /bitnami/discourse
              subPath: discourse/discourse
        - name: sidekiq
          image: {{ &discourseStack.sidekiqImageName }}:{{ &discourseStack.sidekiqImageVersion }}
          imagePullPolicy: IfNotPresent
          command: ["./app-entrypoint.sh", "nami", "start", "--foreground", "discourse-sidekiq"]
          env:
            - name: DISCOURSE_POSTGRESQL_NAME
              value: bitnami_application
            - name: DISCOURSE_POSTGRESQL_USERNAME
              value: bn_discourse
            - name: DISCOURSE_POSTGRESQL_PASSWORD
              value: bitnami1
            - name: DISCOURSE_HOST
              value: discourse-stack-service
            - name: DISCOURSE_PORT
              value: "3000"
            - name: POSTGRESQL_HOST
              value: localhost
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: REDIS_HOST
              value: localhost
            - name: REDIS_PORT_NUMBER
              value: "6379"
            - name: DISCOURSE_SITE_NAME
              value: {{ discourseStack.discourseSiteName }}
          volumeMounts:
            - name: discourse-data
              mountPath: /bitnami/discourse
              subPath: discourse/sidekiq
        - name: postgresql
          image: {{ &discourseStack.postgresqlImageName }}:{{ &discourseStack.postgresqlImageVersion }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: discourse-data
              mountPath: /bitnami/postgresql
              subPath: discourse/postgresql
        - name: redis
          image: {{ &discourseStack.redisImageName }}:{{ &discourseStack.redisImageVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          volumeMounts:
            - name: discourse-data
              mountPath: /bitnami/redis
              subPath: discourse/redis
      volumes:
        - name: discourse-data
          persistentVolumeClaim:
            claimName: testlab-internal-claim
---
apiVersion: v1
kind: Service
metadata:
  name: discourse-stack-service
  namespace: {{ namespace }}
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: discourse-stack
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: discourse-stack-ingress
  namespace: {{ namespace }}
spec:
  rules:
  - host: testlab-discourse.test-datalabs.nerc.ac.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: discourse-stack-service
          servicePort: 3000
