---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
      name: minio-{{ .Values.datalabVolume }}
  name: minio-{{ .Values.datalabVolume }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.minio.replicas }}
  template:
    metadata:
      labels:
        name: minio-{{ .Values.datalabVolume }}
        user-pod: minio
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          args: ["-c", "chmod 777 /mnt/glusterfs"]
          volumeMounts:
            - mountPath: /mnt/glusterfs
              name: glusterfsvol
      containers:
        - name: minio
          image: {{ .Values.minio.imageName }}:{{ .Values.minio.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-shared-store-secret
                  key: accessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-shared-store-secret
                  key: secretKey
          args: ["server", "/mnt/glusterfs"]
          volumeMounts:
            - mountPath: /mnt/glusterfs
              name: glusterfsvol
          livenessProbe:
            httpGet:
              path: /minio/login
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: minio-connect
          image: {{ .Values.minio.connectImage }}:{{ .Values.minio.connectVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ORIGIN
              value: {{ .Values.domain }}
            - name: ACTIONS
              value: "['set']"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: glusterfsvol
          persistentVolumeClaim:
            claimName: {{ .Values.datalabVolume }}-claim
---
apiVersion: v1
kind: Service
metadata:
  name: minio-{{ .Values.datalabVolume }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: minio-{{ .Values.datalabVolume }}-ui
      port: 80
      targetPort: 9000
    - name: minio-{{ .Values.datalabVolume }}-connect
      port: 81
      targetPort: 80
  selector:
    name: minio-{{ .Values.datalabVolume }}
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio-{{ .Values.datalabVolume }}
  namespace: {{ .Values.namespace }}
  annotations:
    ingress.kubernetes.io/auth-url: {{ .Values.authService }}/auth
    ingress.kubernetes.io/auth-signin: {{ .Values.authSignin }}
    ingress.kubernetes.io/proxy-body-size: {{ .Values.maxBodySize }}
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - {{ .Values.datalabName }}-{{ .Values.datalabVolume }}.{{ .Values.domain }}
    secretName: tls-secret
  rules:
  - host: {{ .Values.datalabName }}-{{ .Values.datalabVolume }}.{{ .Values.domain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: minio-{{ .Values.datalabVolume }}
            servicePort: 80
        - path: /connect
          backend:
            serviceName: minio-{{ .Values.datalabVolume }}
            servicePort: 81
