version: '3'
services:
  nginx:
    image: nginx:1.13.3
    ports:
    - 443:443
    volumes:
    - ${PWD}/tls.key:/etc/ssl/private/datalabskey.pem
    - ${PWD}/tls.crt:/etc/ssl/certs/datalabs.pem
    - ${PWD}/datalab.conf:/etc/nginx/conf.d/datalab.conf
