---
apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler-dashboard
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8787
      targetPort: 8787
      protocol: TCP
  selector:
    app: dask-scheduler
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8786
      targetPort: 8786
      protocol: TCP
  selector:
    app: dask-scheduler
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dask-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    ingress.kubernetes.io/auth-url: {{ .Values.authService }}/auth
    ingress.kubernetes.io/auth-signin: {{ .Values.authSignin }}
spec:
  tls:
  - hosts:
    - {{ .Values.datalabName }}-dask.{{ .Values.domain }}
    secretName: tls-secret
  rules:
  - host: {{ .Values.datalabName }}-dask.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: dask-scheduler-dashboard
          servicePort: 8787
