---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dask-workers-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.daskWorker.replicas }}
  template:
    metadata:
      labels:
        app: dask-workers
        environment: {{ .Values.environment }}
    spec:
      containers:
      - name: dask-worker
        image: {{ .Values.daskWorker.imageName }}:{{ .Values.daskWorker.version }}
        imagePullPolicy: IfNotPresent
        env:
          - name: DASK_ROLE
            value: WORKER
          - name: SCHEDULER
            value: dask-scheduler:8786
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 4Gi
