---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dask-scheduler-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dask-scheduler
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: dask-scheduler
          image: {{ .Values.daskScheduler.imageName }}:{{ .Values.daskScheduler.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8787
            - containerPort: 8786
          env:
            - name: DASK_ROLE
              value: SCHEDULER
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
