apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datalab-api-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.datalabApi.replicas }}
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: datalab-api
        environment: {{ .Values.environment }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/datalab-api: {{ .Values.datalabApi.policy }}
    spec:
      containers:
        - name: datalab-api
          image: {{ .Values.datalabApi.imageName }}:{{ .Values.datalabVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATALAB_NAME
              value: {{ .Values.datalabName }}
            - name: DATABASE_HOST
              value: mongo-service
            - name: INFRASTRUCTURE_API
              value: http://infrastructure-api-service:8000
            - name: VAULT_APP_ROLE
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: secret
            - name: VAULT_API
              value: http://vault-service:8200
            - name: AUTHORISATION_SERVICE
              value: http://datalab-auth-service
          livenessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: datalab-api-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: api
      port: 8000
      targetPort: 8000
  selector:
    app: datalab-api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: datalab-api-ingress
  namespace: {{ .Values.namespace }}
spec:
  tls:
  - hosts:
    - {{ .Values.datalabName }}-api.{{ .Values.domain }}
    secretName: tls-secret
  rules:
  - host: {{ .Values.datalabName }}-api.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: datalab-api-service
          servicePort: 8000
