apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongo.imageName }}:{{ .Values.mongo.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          livenessProbe:
            exec: 
              command:
                - mongo
                - --eval
                - "db.serverStatus()"
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: mongodb-volume-1
              mountPath: /data/db
              subPath: mongodb
      volumes:
        - name: mongodb-volume-1
          persistentVolumeClaim:
            claimName: {{ .Values.datalabVolume }}-internal-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
  type: NodePort
