---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-worker
  namespace: {{ .Values.namespace }}
  labels:
    name: spark-worker
spec:
  replicas: {{ .Values.sparkWorker.replicas }}
  template:
    metadata:
      labels:
        name: spark-worker
        environment: {{ .Values.environment }}
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: spark-worker
        image: {{ .Values.sparkWorker.imageName }}:{{ .Values.sparkWorker.version }}
        imagePullPolicy : "IfNotPresent"
        ports:
        - containerPort: 7078
          protocol: TCP
        env:
        - name: SPARK_ROLE
          value: WORKER
        - name: R_LIBS_USER
          value: {{ .Values.sharedRLibs }}
        volumeMounts:
          - mountPath: /data
            name: glusterfsvol
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 2
            memory: 4Gi
      volumes:
        - name: glusterfsvol
          persistentVolumeClaim:
            claimName: {{ .Values.datalabVolume }}-claim
