---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-master
  namespace: {{ .Values.namespace }}
  labels:
    name: spark-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spark-master
        environment: {{ .Values.environment }}
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name : spark-master
        image: {{ .Values.sparkMaster.imageName }}:{{ .Values.sparkMaster.version }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 7077
          protocol: TCP
        env:
        - name: SPARK_ROLE
          value: MASTER
        - name: R_LIBS_USER
          value: {{ .Values.sharedRLibs }}
        volumeMounts:
          - mountPath: /data
            name: glusterfsvol
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 2
            memory: 4Gi
      volumes:
        - name: glusterfsvol
          persistentVolumeClaim:
            claimName: {{ .Values.datalabVolume }}-claim
